site_name: My Docs
theme:
  name: material
  features:
    - navigation.tabs        # top tabs
    - navigation.tabs.sticky # keep them visible on scroll (optional)

nav:
  - Home: index.md
  - About: about.md
  - ACC: acc.md
  - BDA: bda.md
